name: dinomaly
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==2.11.7
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.13.3
      - black==22.3.0
      - bleach==6.1.0
      - blessed==1.20.0
      - blessings==1.7
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.6
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - croniter==1.3.15
      - cryptography==44.0.2
      - cycler==0.12.1
      - dateutils==0.6.12
      - db-tsw==0.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - deepdiff==7.0.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - editor==1.6.6
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - execnet==2.1.1
      - executing==2.2.0
      - fastapi==0.115.12
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2023.12.2
      - ftfy==6.2.3
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - geffnet==1.0.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - gql==3.5.2
      - gradio==3.50.0
      - gradio-client==0.6.1
      - graphql-core==3.2.4
      - grpcio==1.70.0
      - gsplat==0.1.3
      - h11==0.14.0
      - h5py==3.11.0
      - hdf5storage==0.1.19
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - id==1.5.0
      - idna==3.10
      - imageio==2.35.1
      - imgaug==0.4.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - inquirer==3.4.0
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==5.10.1
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keyring==25.5.0
      - kiwisolver==1.4.7
      - kornia==0.6.7
      - lazy-object-proxy==1.10.0
      - libigl==2.5.1
      - lightning==2.1.0
      - lightning-cloud==0.5.37
      - lightning-utilities==0.11.9
      - lit==18.1.8
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.6.0
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-collections==0.1.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.36.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nh3==0.2.21
      - ninja==1.11.1.4
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==1.23.3
      - numpy-stl==3.1.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.6.0.66
      - ordered-set==4.1.0
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.3.5
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - plyfile==1.0.3
      - portalocker==3.0.0
      - pot==0.9.5
      - power-spherical==0.1.0
      - prettytable==3.11.0
      - progressbar==2.5
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - protobuf==4.25.6
      - psutil==6.1.1
      - ptflops==0.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyjwt==2.9.0
      - pylint==2.13.4
      - pyparsing==3.1.4
      - pyproject-hooks==1.2.0
      - pysocks==1.7.1
      - pytest==7.1.2
      - pytest-forked==1.6.0
      - pytest-xdist==2.5.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - python-utils==3.8.2
      - pytorch-lightning==2.1.0
      - pytorch-msssim==1.0.0
      - pytubefix==8.12.3
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==26.3.0
      - readchar==4.2.1
      - readme-renderer==43.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.20.1
      - rsa==4.9
      - ruff==0.11.7
      - runs==1.2.2
      - safetensors==0.5.3
      - scienceplots==2.1.1
      - scikit-image==0.19.3
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - shapely==2.0.7
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.44.0
      - starsessions==1.3.0
      - submitit==1.5.2
      - subprocess32==3.5.4
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.4.5
      - tinycss2==1.2.1
      - tokenize-rt==6.0.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.0.1
      - torchdiffeq==0.2.5
      - torchmetrics==1.5.2
      - torchprofile==0.0.4
      - torchvision==0.15.2
      - tornado==6.4.2
      - tqdm==4.64.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==2.0.0
      - twine==6.1.0
      - typeguard==4.4.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.0
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.33.0
      - wandb==0.15.0
      - watchdog==4.0.2
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xmod==1.8.1
      - yacs==0.1.8
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/vsw/miniconda3/envs/dinomaly
