name: rvt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blosc=1.21.1=hd32f23e_0
  - blosc-hdf5-plugin=1.0.0=h8dde25b_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - hdf5=1.12.1=h2b7332f_3
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.14.1=hc1efc7f_1
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - mock=4.0.3=pyhd3eb1b0_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - python_abi=3.9=2_cp39
  - readline=8.3=hc2a1206_0
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bbox-visualizer==0.1.0
      - beautifulsoup4==4.13.4
      - black==25.1.0
      - blosc2==2.5.1
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.8
      - clip==1.0
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - crcmod==1.7
      - cryptography==45.0.6
      - cupy-cuda11x==13.5.1
      - cycler==0.12.1
      - decorator==4.4.2
      - detectron2==0.6
      - docker-pycreds==0.4.0
      - einops==0.6.0
      - einx==0.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastrlock==0.8.3
      - filelock==3.14.0
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h5py==3.8.0
      - hdf5plugin==4.4.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iopath==0.1.9
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lit==15.0.7
      - llvmlite==0.43.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - metavision==0.0.3
      - ml-collections==0.1.1
      - mmcv==2.0.1
      - mmengine==0.10.7
      - model-index==0.1.11
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - natsort==8.4.0
      - ndindex==1.10.0
      - networkx==3.2.1
      - ninja==1.13.0
      - numba==0.60.0
      - numexpr==2.10.0
      - numpy==1.22.0
      - omegaconf==2.3.0
      - onnx==1.12.0
      - onnxruntime==1.19.2
      - opencv-python==4.6.0.66
      - opendatalab==0.0.10
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==1.5.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.3.8
      - plotly==5.13.1
      - portalocker==3.2.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==3.20.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.6
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytorch-lightning==1.8.6
      - pytz==2023.4
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.0
      - scikit-image==0.22.0
      - scikit-learn==1.6.1
      - scipy==1.11.4
      - seaborn==0.13.2
      - sentry-sdk==2.34.1
      - setproctitle==1.3.6
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - spikingjelly==0.0.0.0.14
      - stack-data==0.6.3
      - strenum==0.4.10
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboard-logger==0.1.0
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.6.12
      - tomli==2.2.1
      - torch==2.0.0+cu118
      - torchaudio==2.0.1+cu118
      - torchdata==0.6.0
      - torchinfo==1.8.0
      - torchmetrics==1.8.1
      - torchvision==0.15.1+cu118
      - tornado==6.5.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - triton==2.0.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
      - visdom==0.2.4
      - wandb==0.14.0
      - warmup-scheduler==0.3
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/vsw/miniconda3/envs/rvt