dataset: 'fdst'
train_json: 'datasets/FDST/train.json'
val_json: 'datasets/FDST/val.json'
test_json: 'datasets/FDST/test.json'
width: 640
height: 360
model: 'XACANNet2s'
uncertainty: False
lr: 0.00005
log_freq: 200
val_freq: 3600