name: cbd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.1.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.0.0
      - platformdirs==4.5.0
      - protobuf==6.33.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentry-sdk==2.42.1
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.22.2
      - wcwidth==0.2.14
      - werkzeug==3.1.3
prefix: /home/vsw/miniconda3/envs/cbd
